
name: MLOps CI

on:
  push:
    paths:
      - 'mlops/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r mlops/requirements.txt

      - name: Test FastAPI App
        run: |
          python -c "import pickle; f=open('mlops/model.pkl','rb'); m=pickle.load(f); print('✅ Model loaded')"
